title: Jean C. Flanagan
tagline: science education specialist and writer
author:
  name: Jean C. Flanagan
  email: jeancflanagan@gmail.com
url: http://jeancflanagan.com
image_url: http://static.oliverpattison.org

pygments: true
layouts: ./_layouts
plugins: ./_plugins
exclude: ['Rakefile', 's3_website.yml']

permalink: /:year/:title/
markdown: kramdown